### ISSUE TITLE
Each consumer/ producer has it's own connection?

### ISSUE THREAD

**Issue by Nikola-Milovic** [wagslane/go-rabbitmq#79] opened 2022-06-05 11:32 UTC
Hello,
 from my understanding of the code, each consumer/ publisher will have its own connection, which contradicts the recommendation of 1 connection per application. In theory, every consumer/ producer should use the same connection but have their own channel? Is this something that's intentional by design, or is there room for improvement here?

**Comment by wagslane** [comment] 2022-06-05 12:31
It's by design. The consumers and producers are thread safe. So when I use this library, I generally just have one producer and one consumer.

**Comment by JFFby** [comment] 2022-09-21 18:14
Hi there,
If consumer and publisher are thread safe, why then comment above `Close` method says that it is not safe to reuse consumet\producer?
https://github.com/wagslane/go-rabbitmq/blob/main/publish.go#L211
https://github.com/wagslane/go-rabbitmq/blob/main/consume.go#L131

**Comment by wagslane** [comment] 2022-10-03 00:42
There is room for improvement here! However, at the moment to use this library effectively you should be creating new consumers for each queue you want to consume from. A given consumer is thread-safe in that you can distribute the work of that consumer across many goroutines.

**Comment by johanneswuerbach** [comment] 2022-10-05 09:08
Should this be more prominently called out or actually produce an error? I've also ran into this by calling `StartConsuming` multiple times to eventually find out only one of them is actually reconnected 🤔

**Comment by Chameleon-m** [comment] 2022-11-29 12:15
https://pkg.go.dev/github.com/rabbitmq/amqp091-go

> It's advisable to use separate connections for Channel.Publish and Channel.Consume so not to have TCP pushback on publishing affect the ability to consume messages, so this parameter is here mostly for completeness.

> Note: RabbitMQ prefers to use TCP push back to control flow for all channels on a connection, so under high volume scenarios, it's wise to open separate Connections for publishings and deliveries.

> Note: RabbitMQ will rather use TCP pushback on the network connection instead of sending basic.flow. This means that if a single channel is producing too much on the same connection, all channels using that connection will suffer, including acknowledgments from deliveries. Use different Connections if you desire to interleave consumers and producers in the same process to avoid your basic.ack messages from getting rate limited with your basic.publish messages.

**Comment by wagslane** [comment] 2022-11-29 21:10
I'm working on a fix for this. I'm thinking the new API will look like this:

```go
conn := NewConnectionManager()
consumer := NewConsumer(conn, ...)
```

Each consumer/publisher would then share an underlying connection manager.

**Comment by aaqaishtyaq** [comment] 2022-11-30 17:38
Hey @wagslane. I was thinking the same thing. 
For my use case, We are creating a new subscriber for a particular Server Sent Event connection. Creating a new connection each time is not ideal. 

I can help with the new API that can support multiple consumers while maintaining a single connection.

**Comment by wagslane** [comment] 2022-11-30 19:14
This should be resolved now on the main branch. Please check the docs and let me know if I missed something.

**Comment by aaqaishtyaq** [comment] 2022-12-01 14:57
Hey @wagslane, We are still re-using the channel. Ideally, for each consumer, we should create a new channel. 

Currently, there are two issues here:
1. RabbitMQ does not detect that the channel is closed and it will not delete temporary queues until the connection is closed (We are using the same channel here once the connection is made, and only updating it on reconnect).
2. No way to set `Qos` for individual consumers as the condition applies to the channel and we are re-using the channel.


How I see is that we need to manage reconnection for multiple channels and update it once and get a new channel for all old channels. Any thoughts?


In this case, As you can see the queue is still up but the consumer is closed (Not the connection).
![image](https://user-images.githubusercontent.com/22131756/205085047-47422a34-f383-4976-a686-a91011cc2a2f.png)

**Comment by wagslane** [comment] 2022-12-01 15:00
Derp. You are correct. I did this too quickly one day without thinking it through. I'll make another update when I have some time. This shouldn't change the API too much, mostly internals

**Comment by wagslane** [comment] 2022-12-01 18:37
okay, please check the `main` branch again.

There is now a single "connection manager" and a "channel manager" for each publisher and consumer. When an issue happens, both reconnect independently. The channel depends on a connection, so first the connection reconnects successfully, then all the channels should reconnect, then consumption and publishing resumes.

 Let me know if you see other issues with this approach.

**Comment by Chameleon-m** [comment] 2022-12-01 19:50
maybe it's time to create a new release tag?)
people are surprised at the interface change in the same version

**Comment by aaqaishtyaq** [comment] 2022-12-02 08:27
The temporary queue is still not getting cleared as the channel is open. Added a [PR](https://github.com/wagslane/go-rabbitmq/pull/95) to close the `channel` once the consumer is stopped. 

Please review the PR. I have tested running multiple temporary consumers and tried to close one of them and still received messages on other consumers. Even the queue is cleared up a few seconds after the consumer stops. 
Let me know if you need anything or code examples to test the code.

**Comment by wagslane** [comment] 2022-12-05 18:00
Resolved in 0.11.0

**Closed by wagslane** 2022-12-05 18:00 UTC

**Comment by tnm0113** [comment] 2023-03-06 04:27
Hi @wagslane , so its safe to reuse Publisher and Consumer now ? I want to init 1 Publisher and reuse in my application

**Comment by Nikola-Milovic** [comment] 2024-03-01 10:28
Same question here, I connect once to rabbitmq, and store it in a pubsub struct that  I share across my app. This struct creates publishers and consumers. I've noticed that my publishers are not sending anything so I am now afraid that it might be related to how channels/ connections are handled

```golang
type PubSub struct {
	conn       *rabbitmq.Conn
	listeners  []Listener
	logger     rabbitmq.Logger
	publishers map[Exchanges]Publisher
}

func New(cfg Config) (*PubSub, error) {
	conn, err := rabbitmq.NewConn(
		fmt.Sprintf("amqp://%s:%s@%s:%s/", cfg.User, cfg.Pass, cfg.Host, cfg.Port),
		rabbitmq.WithConnectionOptionsReconnectInterval(time.Second*3),
	)
	if err != nil {
		return &PubSub{}, fmt.Errorf("failed to connect, %w", err)
	}
```
