### ISSUE TITLE
Consumer won't reconnect

### ISSUE THREAD

**Issue by nicklaros** [wagslane/go-rabbitmq#47] opened 2021-11-06 10:02 UTC
Hi,

Somehow when network got disconnected for a minutes or so and then network up again, I got a log 
```
gorabbit: rabbit consumer goroutine closed
``` 
After that, consumer stops receiving new message.
Why wont it reconnect?

I'm using version 0.6.2, and my code is (more or less) like this
```
rabbitmqConsumer, err := rabbitmq.NewConsumer(config.constructURL(), amqp.Config{}, rabbitmq.WithConsumerOptionsLogging)
...
rabbitmqConsumer.StartConsuming(
  func(message rabbitmq.Delivery) bool {
    return true
  },
  "",
  []string{""},
  func(options *rabbitmq.ConsumeOptions) {
    options.QueueExclusive = true
    options.ConsumerExclusive = true
    options.QueueDurable = true
    options.BindingExchange = &rabbitmq.BindingExchangeOptions{
      Name:    "my_rabbitmq_topic",
      Kind:    "fanout",
      Durable: true,
    }
  },
)
```

**Comment by nicklaros** [comment] 2021-11-06 10:11
https://github.com/wagslane/go-rabbitmq/blob/4d14909a3fed0e3a1466b7eb3818b6050f803348/consume.go#L259

Looks like msgs channel is closed causing it to print log from this line

https://github.com/wagslane/go-rabbitmq/blob/4d14909a3fed0e3a1466b7eb3818b6050f803348/consume.go#L282

So how to make it start consuming again?

**Comment by miketonks** [comment] 2021-11-29 16:31
Any update on this?  Does the library handle Automatic reconnection as stated in the README or not?

I'm looking for a library that does this, so if we can use this one that would be ideal, but need to know if it works.

**Comment by wagslane** [comment] 2021-11-29 17:03
It is supposed to yes, I haven't had time to dive in on this bug yet. I'll try to take a look this week

**Comment by miketonks** [comment] 2021-11-29 17:19
Thanks.  It does seem to reconnect fine.

I did a simple test by runnung rabbitmq server in a docker container.  After restarting the docker container, the consumer reconnected automatically:

https://github.com/wagslane/go-rabbitmq/blob/4d14909a3fed0e3a1466b7eb3818b6050f803348/channel.go#L61

```
2021/11/29 17:14:52 consumed: Hello World!
2021/11/29 17:14:53 consumed: Hello World!
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: attempting to reconnect to amqp server after close
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: waiting 1s seconds to attempt to reconnect to amqp server
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:58 gorabbit: rabbit consumer goroutine closed
2021/11/29 17:14:59 gorabbit: error reconnecting to amqp server: Exception (501) Reason: "read tcp 127.0.0.1:54752->127.0.0.1:5672: read: connection reset by peer"
2021/11/29 17:14:59 gorabbit: waiting 2s seconds to attempt to reconnect to amqp server
2021/11/29 17:15:01 gorabbit: error reconnecting to amqp server: dial tcp 127.0.0.1:5672: connect: connection refused
2021/11/29 17:15:01 gorabbit: waiting 4s seconds to attempt to reconnect to amqp server
2021/11/29 17:15:05 gorabbit: error reconnecting to amqp server: Exception (501) Reason: "read tcp 127.0.0.1:54858->127.0.0.1:5672: read: connection reset by peer"
2021/11/29 17:15:05 gorabbit: waiting 8s seconds to attempt to reconnect to amqp server
2021/11/29 17:15:13 gorabbit: successfully reconnected to amqp server after close
2021/11/29 17:15:13 gorabbit: consume cancel/close handler triggered. err: Exception (320) Reason: "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2021/11/29 17:15:13 gorabbit: waiting 1s seconds to attempt to start consumer goroutines
2021/11/29 17:15:14 gorabbit: Processing messages on 10 goroutines
2021/11/29 17:15:14 consumed: Hello World!
2021/11/29 17:15:14 consumed: Hello World!
```

Looks good to me :+1:

**Comment by wagslane** [comment] 2021-11-29 17:21
Thanks for running that little test! I'll still take a look at the above
report, but this helps me check some boxes :)

**Comment by wagslane** [comment] 2021-12-07 15:18
@nicklaros Do you ever see these logs? `attempting to reconnect to amqp server after close`

We do an exponential backoff by default, and I'm wondering if with a long disconnect time you were getting backoff retries with 2 min+ wait times

**Comment by phillip-o** [comment] 2022-01-11 22:04
I'm having trouble with reconnects too on v0.7.0. Simulating connection loss by stopping an active port forwarding from a Kubernetes cluster, followed by opening it again a few seconds later.

`2022/01/11 22:55:02 gorabbit: rabbit consumer goroutine closed`

..but nothing else after 10 minutes.

Any tricks I could try? I'm a rookie user of this module, so I wouldn't be surprised if I'm doing something wrong on my end.

**Comment by wagslane** [comment] 2022-02-28 00:38
I'm sorry I'm not able to reproduce this. Are you guys sure you aren't missing some logging, and that messages are actually being sent?

This is my test process. Let me know what to do differently to see what you're seeing:

1. Start example consumer connected to local rabbitmq
2. Close local rabbit server
3. Watch consumer auto reconnect

```
2022/02/27 17:34:30 gorabbit: attempting to reconnect to amqp server after close
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: waiting 1s seconds to attempt to reconnect to amqp server
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:30 gorabbit: rabbit consumer goroutine closed
2022/02/27 17:34:31 gorabbit: error reconnecting to amqp server: dial tcp 127.0.0.1:5672: connect: connection refused
2022/02/27 17:34:31 gorabbit: waiting 2s seconds to attempt to reconnect to amqp server
2022/02/27 17:34:33 gorabbit: error reconnecting to amqp server: dial tcp 127.0.0.1:5672: connect: connection refused
2022/02/27 17:34:33 gorabbit: waiting 4s seconds to attempt to reconnect to amqp server
2022/02/27 17:34:37 gorabbit: error reconnecting to amqp server: dial tcp 127.0.0.1:5672: connect: connection refused
2022/02/27 17:34:37 gorabbit: waiting 8s seconds to attempt to reconnect to amqp server
2022/02/27 17:34:45 gorabbit: error reconnecting to amqp server: dial tcp 127.0.0.1:5672: connect: connection refused
2022/02/27 17:34:45 gorabbit: waiting 16s seconds to attempt to reconnect to amqp server


2022/02/27 17:35:01 gorabbit: successfully reconnected to amqp server after close
2022/02/27 17:35:01 gorabbit: gorabbit: successful recovery from: Exception (320) Reason: "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2022/02/27 17:35:01 gorabbit: waiting 1s seconds to attempt to start consumer goroutines
2022/02/27 17:35:03 gorabbit: Processing messages on 10 goroutines
```
4. Start publisher, watch the consumer consume the messages
5. Close cleanly both the publisher and consumer

**Comment by phillip-o** [comment] 2022-02-28 11:15
Thanks for having a look into this @wagslane 👍

Speaking for myself, I'm sure there aren't other logs and I certainly can't imagine messages flowing through after having closed the forwarded connection into the kubernetes cluster.

I did not try to run a local RabbitMQ server tho, I could ofcourse see if that makes any difference.

**Comment by tmalaher** [comment] 2022-03-04 02:03
> I'm sorry I'm not able to reproduce this. Are you guys sure you aren't missing some logging, and that messages are actually being sent?
> 
> This is my test process. Let me know what to do differently to see what you're seeing:
> 
> 1. Start example consumer connected to local rabbitmq
> 2. Close local rabbit server
> 3. Watch consumer auto reconnect
> 4. Start publisher, watch the consumer consume the messages
> 5. Close cleanly both the publisher and consumer

Note that this is *not* my use case. My case is:

1. Start remote server
2. Start local consumer
3. Watch consumer receive messages
4. ...long period of inactivity...
5. See message `gorabbit: rabbit consumer goroutine closed` in the consumer log
6. Publish more messages
7. messages are not picked up by consumer
8. Stop local consumer
9. Start new local consumer
10. Messages are received

So it seems like the consumer gets bored and drops the connection and does not reconnect.

**Comment by fortyanov** [comment] 2022-03-10 13:04
It may helps #62

**Comment by wagslane** [comment] 2022-03-11 02:03
@tmalaher I just published a new version with some more logging as I'm still not able to reproduce this error. There is a case where the an error is initiated by the client, or where the channel is closed gracefully that we don't attempt (and shouldn't attempt) to reconnect. Can you try with the new logs? Hopefully they will give us some more insight into what is causing this "boredom"

**Comment by ruinshe** [comment] 2022-03-25 07:50
Hi all, I managed to reproduce this issue in latest version `0.7.2` and the logs attached below, could you take a look?

```log
2022/03/24 18:49:05 gorabbit: Processing messages on 1 goroutines
2022/03/25 10:16:19 gorabbit: rabbit consumer goroutine closed
2022/03/25 10:16:19 gorabbit: not attempting to reconnect to amqp server because closure was initiated by the client
2022/03/25 10:16:19 gorabbit: not attempting to reconnect to amqp server because closure was initiated by the client
```

What I did is, manually disable my computer's network for a while and re-enable the network.

**Comment by wagslane** [comment] 2022-03-31 21:51
@ruinshe Can you please try again with 0.7.3? The new logs should show us exactly which error you are getting. Basically we just need to keep whitelisting the various errors that make sense to reconnect on from the AMQP lib

**Comment by tmalaher** [comment] 2022-04-01 01:34
I've narrowed this down, I think, to when my (RedHat Linux 8.5) laptop hibernates.
With 0.7.2, I get this:
2022/03/31 19:26:39 gorabbit: not attempting to reconnect to amqp server because closure was initiated by the client
2022/03/31 19:26:39 gorabbit: not attempting to reconnect to amqp server because closure was initiated by the client
2022/03/31 19:26:39 gorabbit: rabbit consumer goroutine closed

I've recompiled with 0.7.3 and I'll let you know if that changes anything.

**Comment by wagslane** [comment] 2022-04-01 14:46
@tmalaher awesome, yes! 0.7.4 should have the reconnect for that error.

**Comment by marcelmiguel** [comment] 2022-04-05 11:20
No reconnecting with 0.7.4 

I've changed channel.go from a fork marcelmiguel/go-rabbitmq to fix the reconnection.

Now seems to work. Need some more testing.

Te reproduce the error:
- from a **spanish W10**, deactivate ethernet
- package detects inmediatelly coms are down.
- activate ethernet
- then after 5s or 10s, is reconnected.

**Comment by marcelmiguel** [comment] 2022-04-05 11:26
Sorry, forget to put the error:

`Exception (501) Reason: "read tcp 192.168.1.150:63236->159.223.6.51:5672: wsarecv: Se ha anulado una conexión establecida por el software en su equipo host.."`

But better not use any spanish phrase, as it can be on any language.

**Comment by wagslane** [comment] 2022-04-05 11:28
Oh lol xD we catch this one in English but not Spanish. Is there an unwrap we can do to catch this in one? Like an errors.Is comparison?

**Comment by wagslane** [comment] 2022-04-05 11:29
I'm hoping io.EOF is the right one.. I can add that

**Comment by tmalaher** [comment] 2022-04-05 13:27
Recompiled with 0.7.4 and now it seems to survive hibernation.
There are *no* log messages produced! I guess this is a good thing, as it means it is ignoring whatever errors the hibernate/wake cycle is causing.

I'll do further torture testing (I hibernate the laptop every day, so plenty of testing over the course of the next week.)

Thanks!

**Comment by wagslane** [comment] 2022-04-05 14:07
@tmalaher Okay with all the feedback from this thread I believe I've solved... all? The reconnection issues in `0.8.0`. I originally was doing clean closure wrong and thats why I had to whitelist the errors, but I don't think I need to anymore, so I can just reconnect on any error because the new `.Close()` method returns a `nil` error.

Sorry about the breaking API change, hopefully it's the last one!

That's what `v0` is for after all haha.

You can also configure your logger, that's probably why you aren't seeing logs.

**Comment by ruinshe** [comment] 2022-04-06 07:51
After upgrading to 0.8.0, it seems works now.

Will keep in mind of it in future, thanks!

**Comment by marcelmiguel** [comment] 2022-04-06 08:08
With 0.8.0, half the time, give this:

```
2022/04/06 10:00:51 gorabbit: closing consumer...
2022/04/06 10:00:51 gorabbit: attempting to reconnect to amqp server after cancel
2022/04/06 10:00:51 gorabbit: rabbit consumer goroutine closed
2022/04/06 10:00:51 gorabbit: waiting 5s seconds to attempt to reconnect to amqp server
```

And sometimes ends like this:
```
2022/04/06 10:03:58 gorabbit: closing consumer...
2022/04/06 10:03:58 gorabbit: rabbit consumer goroutine closed
2022/04/06 10:03:58 gorabbit: amqp channel closed gracefully
```

**Comment by wagslane** [comment] 2022-04-06 09:34
@marcelmiguel what are you doing differently, or what different thing is happening when it tries to reconnect? That's the cancel message, which logic actually didn't change in 0.8.0

**Comment by marcelmiguel** [comment] 2022-04-07 07:28
@wagslane This is happening when **closing**  a connection via Close(), I didn't test it before v0.8.0. 
It is not a real problem for me, because the app closes before a reconnection is alive, but seems that the closgin method does not disable reconnection.

**Comment by wagslane** [comment] 2022-04-24 02:24
I'm going to close this thread. I added some more logging @marcelmiguel to 0.8.1 because I think this might be something different. If you're still having issues please open a new issue.

**Closed by wagslane** 2022-04-24 02:24 UTC
